### ISSUE TITLE
key must be a string, a buffer or an object error

### ISSUE THREAD

**Issue by suleymanbyzt** [DrPaulBrewer/zip-bucket-bin#1]
Hello,
When I try to upload using your library, I get error like below.

`zip-bucket --progress --key C:\Users\user\repos\bucket-admin.json gs://spaces/m3qwX8/2484cdd8f7d38d2d2fe0030.zip gs://spaces/m3qwX8/test.zip`

uploading zip file to gs://spaces/m3msX8/test.zip

TypeError: key must be a string, a buffer or an object
    at typeError (C:\Users\user\AppData\Roaming\nvm\v18.17.0\node_modules\zip-bucket-bin\node_modules\jwa\index.js:115:10)
    at checkIsPrivateKey (C:\Users\user\AppData\Roaming\nvm\v18.17.0\node_modules\zip-bucket-bin\node_modules\jwa\index.js:61:9)
    at Object.sign (C:\Users\user\AppData\Roaming\nvm\v18.17.0\node_modules\zip-bucket-bin\node_modules\jwa\index.js:147:5)
    at Object.jwsSign [as sign] (C:\Users\user\AppData\Roaming\nvm\v18.17.0\node_modules\zip-bucket-bin\node_modules\jws\lib\sign-stream.js:32:24)
    at JWTAccess.getRequestHeaders (C:\Users\user\AppData\Roaming\nvm\v18.17.0\node_modules\zip-bucket-bin\node_modules\google-auth-library\build\src\auth\jwtaccess.js:123:31)
    at JWT.getRequestMetadataAsync (C:\Users\user\AppData\Roaming\nvm\v18.17.0\node_modules\zip-bucket-bin\node_modules\google-auth-library\build\src\auth\jwtclient.js:86:51)
    at JWT.getRequestHeaders (C:\Users\user\AppData\Roaming\nvm\v18.17.0\node_modules\zip-bucket-bin\node_modules\google-auth-library\build\src\auth\oauth2client.js:261:37)
    at GoogleAuth.authorizeRequest (C:\Users\user\AppData\Roaming\nvm\v18.17.0\node_modules\zip-bucket-bin\node_modules\google-auth-library\build\src\auth\googleauth.js:666:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

can you help me what my mistake is

**Comment by suleymanbyzt** [comment]
oops i found my problem :D i deleted this bucket so i was getting an error. Thank you man you're the best !
